name: CI
on:
  push:
    branches:
      - main

jobs:
  build_on_win:
    runs-on: windows-19
    steps:
    - uses: actions/checkout@master
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: see directory
      run: ls
